name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Verify dependencies
        run: go mod verify

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2023.1.7"
          install-go: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=5m

      - name: Test
        run: go test -race -count 10 -vet=off ./...
